# Generated by Django 4.0.1 on 2023-02-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubmessage',
            name='club',
        ),
        migrations.AddField(
            model_name='club',
            name='messages',
            field=models.ManyToManyField(related_name='clubs', to='clubs.ClubMessage'),
        ),
    ]
